version: "3.9"

services:
    web:
        build: .
        container_name: my_laravel_app
        restart: unless-stopped
        tty: true
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: chat
            DB_USERNAME: root
            DB_PASSWORD: 123123
            APP_ENV: local
            APP_DEBUG: true
            APP_KEY: base64:3n3BWf2EtVagIhDsIMa+j9i86CWYyweo5dqZqF1SgbA=
        volumes:
            - ./:/var/www/html
            - ./public:/var/www/html/public
        ports:
            - "8000:8000"
            - "8080:8080"
            - "9000:9000"
        networks:
            - my_network

    # PostgreSQL database container
    db:
        image: postgres
        container_name: my_laravel_app_db
        restart: unless-stopped
        volumes:
            - pg_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 123123
            POSTGRES_DB: chat
        ports:
            - "5432:5432"
        networks:
            - my_network

    # PgAdmin container
    pgadmin:
        image: dpage/pgadmin4
        container_name: my_pgadmin_container
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
            PGADMIN_DEFAULT_PASSWORD: "123"
        ports:
            - "5050:80"
        networks:
            - my_network

    # Nginx container
    nginx:
        image: nginx:latest
        container_name: my_laravel_app_nginx
        restart: unless-stopped
        ports:
            - "8081:8081"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - web
        networks:
            - my_network

volumes:
    pg_data:

networks:
    my_network:
        driver: bridge
